version: '3.8'

services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      # Database Connection String for PostgreSQL
      - DATABASE_URL=postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-password123}@db:5432/${POSTGRES_DB:-portfolio_db}
      - NODE_ENV=production
      - RUN_LOCAL=true
      # Example domain mapping for Coolify or traefik
      - SERVICE_FQDN_WEB_5000=https://kevin.syonin.site
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password123}
      POSTGRES_DB: ${POSTGRES_DB:-portfolio_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
